channels:
- currentCSV: ibm-elastic-stack-operator.v3.1.4
  name: dev
- currentCSV: ibm-elastic-stack-operator.v3.1.4
  name: beta
- currentCSV: ibm-elastic-stack-operator.v3.1.3
  name: stable-v1
defaultChannel: stable-v1
packageName: ibm-elastic-stack-operator-app
