{{- if .Values.kibana.install }}
{{ template "elk.settings.all.prepare" . -}}
{{- if eq  "ingress" .Values.kibana.access }}
#
# Copyright 2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "kibana.fullname" . }}-ingress"
  labels:
    app: "{{ template "elasticsearch.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.kibana.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
{{- if .Values.kibana.ingress.labels }}
{{ toYaml .Values.kibana.ingress.labels | indent 4 }}
{{- end }}
  annotations:
    kubernetes.io/ingress.class: "ibm-icp-management"
    icp.management.ibm.com/secure-backends: {{ if .Values.kibana.https }}"true"{{ else }}"false"{{ end }}
{{- if not .Values.kibana.routerEnabled }}
    # Tells ingress to keep the /kibana context root
    icp.management.ibm.com/rewrite-target: "/"
{{- end }}
{{- if .Values.kibana.ingress.annotations }}
{{ toYaml .Values.kibana.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.kibana.ingress.path }}
        backend:
          serviceName: {{ .Values.kibana.name }}
          servicePort: {{ .Values.kibana.internal }}
{{- end -}}
{{- end -}}
